Repository reactor/reactor-kotlin-extensions, pull requests merged in 2022-06, with the labels that each got.

#48 Adapt to addons sumBigInteger changes, upgrade Reactor
  gradle/libs.versions.toml
  src/test/kotlin/reactor/kotlin/extra/math/MathFluxExtensionsTests.kt
Labels: type/chore, type/dependency-upgrade

#47 Fix deprecation notice wording: to be removed in 1.2.0
  src/main/kotlin/reactor/kotlin/extra/swing/SwtSchedulerExtensions.kt
Labels: type/documentation

#46 Deprecate extensions for RxJava2, Repeat and Retry
  src/main/kotlin/reactor/kotlin/adapter/rxjava/RxJava2AdapterExt.kt
  src/main/kotlin/reactor/kotlin/extra/retry/RepeatExtensions.kt
  src/main/kotlin/reactor/kotlin/extra/retry/RetryExtensions.kt
Labels: type/chore, warn/deprecation

#49 Upgrade to Kotlin 1.7, Dokka 1.6.21 for now
  gradle/libs.versions.toml
Labels: type/dependency-upgrade

#44 Polish snippets in README
  README.md
Labels: type/documentation

#51 Dokka now also at v1.7
  gradle/libs.versions.toml
Labels: type/dependency-upgrade
